### ISSUE TITLE
location option ignored

### ISSUE THREAD

**Issue by tslocke** [solidjs/solid-testing-library#65]
This might be related to #60 - I'm also using vitest.

The following test fails:

```js
import { render, screen} from '@solidjs/testing-library'
import { Route, Router } from "@solidjs/router"

test.only('render location', async () => {
  render(Component, {location: '/foo'})
  expect(await screen.findByText('foo')).toBeTruthy()
})

function Component() {
  return (
    <Router>
      <Route path='/' component={() => <p>root</p>}/>
      <Route path='/foo' component={() => <p>foo</p>}/>
    </Router>
  )
}
```

If I change the findByText to 'root' it passes. Am I using the API correctly?

**Comment by atk** [comment]
Actually, the router is already supplied by the test, so wrapping it in another router could break it.

**Comment by tslocke** [comment]
Does that mean I can't test my top-level `<App/>` component (which contains a router)?

Also this still fails for me - any advice?

```js
test('render location', async () => {
  render(() => <Route path='/foo' component={() => <p>foo</p>}/>, {location: '/foo'})
  expect(await screen.findByText('foo')).toBeTruthy()
})
```

Thanks for your help

**Comment by atk** [comment]
That is strange, because this is very close to what we do in our tests: https://github.com/solidjs/solid-testing-library/blob/main/src/__tests__/routes.tsx#L18

**Comment by tslocke** [comment]
I've created a minimal repo with my test above and the test you linked. Both are failing for me

https://github.com/tslocke/solid-router-issue

**Comment by atk** [comment]
Thanks for the repro. I'll test it later.

**Comment by tslocke** [comment]
Any update on this? I'm unable to upgrade to the latest router because I can't get tests passing.

**Comment by atk** [comment]
Sorry, I updated our testing library and everything worked as expected. Maybe the references to older versions broke something, so I'll release the updated version right away.

**Comment by atk** [comment]
OK, I just published 0.8.9 and tested a bit more. Encapsulated routers do not yet work. I'm not sure if I will be able to support them, because we need an in-memory router for that and I don't know if I can inject it by default.

**Comment by tslocke** [comment]
Thanks very much for looking at this. I updated all the deps in that sample repo (and pushed) and the tests still fail for me. Is that expected? I'm not sure what you mean by "encapsulated" routers.

**Comment by atk** [comment]
Basically, testing your app.tsx.

**Comment by tslocke** [comment]
OK. Not a problem for me at the moment. But right now I'm stuck on @solidjs/router 0.8 because the new router only supports things like `useLocation` when the component is inside a route, and as soon as I put things in a route the testing library doesn't render anything, e.g. this fails

```ts
test('render location', async () => {
  render(() => <Route path='/foo' component={() => <p>foo</p>}/>, {location: '/foo'})
  expect(await screen.findByText('foo')).toBeTruthy()
})
```

Repro: https://github.com/tslocke/solid-router-issue

**Comment by atk** [comment]
You can wrap useLocation in catchError in order to make the component work outside of the router. I'm sorry, but I cannot possibly support multiple versions of solid-router.

**Comment by atk** [comment]
This is a module loading issue (we had a lot of those already). Maybe try making the router an external import.

**Comment by tslocke** [comment]
Can you explain a bit more? I thought external imports were part of the build config and therefore would not affect testing?

**Comment by atk** [comment]
vitest internally uses vite to transform the files loaded. However, it has multiple mechanisms to load files - via node modules resolution or its internal resolver. Whenever file transformation fails in vitest, it's usually due to a mix-up between those modes (or in case of solid because it gets resolved twice over the different modes - solid may only be loaded once).

**Comment by egtwp** [comment]
@atk but the problem is only fired with solid-testing-library embedded router.

look at this:

```tsx
import { createSignal, catchError } from "solid-js";
import { render, fireEvent } from "@solidjs/testing-library";
import { A, Route, Router, useParams } from "@solidjs/router";

describe("location option", () => {
  const Ids = () => (
    <>
      <p>Id: {useParams()?.id}</p>
      <p>
        <A href="/ids/9999" noScroll>
          navigate
        </A>
      </p>
    </>
  );
  const App = () => (
    <>
      <Route path="/ids/:id" component={Ids} />
      <Route path="/" component={() => <p>Start</p>} />
    </>
  );

  it("can render the main route with embedded router", async () => {
    const { findByText } = render(() => <App />, { location: "/" });
    expect(await findByText("Start")).not.toBeFalsy();
  });

  it("can render the main route with manually loaded router", async () => {
    const { findByText } = render(() => <Router><App /></Router>);
    expect(await findByText("Start")).not.toBeFalsy();
  });

});
```

```out
stderr | src/routerino.test.tsx > location option > can render the main route with embedded router
Error attempting to initialize @solidjs/router:
"Unknown file extension ".jsx" for /workspaces/Saturday/node_modules/@solidjs/router/dist/index.jsx"

 ❯ src/routerino.test.tsx (2) 1051ms
   ❯ location option (2) 1050ms
     × can render the main route with embedded router 1024ms
     ✓ can render the main route with manually loaded router
```

**Comment by egtwp** [comment]
In my env adding this conf to vitest seems to resolve the issue without break any other tests

```ts
server: {
  deps: {
    inline: ["solid-js", "@solidjs/testing-library", "@solidjs/router"],
  }
}
```

how this sounds to you? I don’t know if could be anyway to not have to add this config manually, what do u think about?

let me know if I can help in any way.

**Comment by tslocke** [comment]
Did this get fixed? I've finally come back to upgrading the my router dep to 0.14 and I'm not having problems any more. It works even without the deps.inline config from @egtwp

**Comment by atk** [comment]
It cannot be fixed in testing-library, but I am preparing a fix in vite-plugin-solid.

**Comment by tslocke** [comment]
I'm no longer seeing that `Unknown file extension ".jsx"`. No idea why. Can't complain : ) But I won't be surprised if it shows up again.

Maybe this issue should be closed, or perhaps renamed to track the issue you are working on in vite-plugin-solid? Up to you.

**Comment by atk** [comment]
I can influence the testing config from the vite-plugin-solid, but not from @solidjs/testing-library.

**Comment by staguer** [comment]
I'm running into this issue. I may have found a workaround using MemoryRouter and its history. Hopefully it will work for me fully.

```typescript
describe("Home", () => {
  test("renders loading state", () => {
    const history = createMemoryHistory();
    history.set({ value: "/home" });
    const rendered = render(() => (
      <MemoryRouter history={history}>
        <Route path={"/home"} component={() => <p>Loading...</p>} />
      </MemoryRouter>
    ));
    expect(rendered.getByText(/Loading/i)).toBeDefined();
  });
});
```

**Comment by atk** [comment]
Since the router integration is removed now, I'll close this issue.
